name: flutter_tdd
description: TDD Clean Architecture for Flutter

version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Service locator
  get_it: ^4.0.1
  # Bloc for state management
  flutter_bloc: ^4.0.0-dev.3
  # Value equality
  equatable: ^1.1.1
  # Functional programming thingies
  dartz: ^0.9.0-dev.6
  # Remote API
  data_connection_checker: ^0.3.4
  http: ^0.12.0+4
  # Local cache
  shared_preferences: ^0.5.6+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1

flutter:
  uses-material-design: true
